### ISSUE TITLE
bib2gls fails with --dir <directory> when <directory> starts with a "." (period).

### ISSUE THREAD

**Issue by LelioC** [nlct/bib2gls#17]
Dear maintainer,

I have been facing the following issue which I believe is a bug.

Consider the attached sample file [test_glossaries.txt](https://github.com/nlct/bib2gls/files/7720528/test_glossaries.txt) (assumed it is named as test_glossaries.tex) taken from the repository examples with the correct .bib files.

When compiling with
```
lualatex --output-dir .tmp test_glossaries.tex
bib2gls --dir .tmp test_glossaries
lualatex --output-dir .tmp test_glossaries.tex
```
the call to bib2gls fails and rises the following error:
```
bib2gls 2.9 (2021-11-22)
Error: Write access forbidden for file: .tmp\test_glossaries.glg
```

However, when considering the following script
```
lualatex --output-dir _tmp test_glossaries.tex
bib2gls --dir _tmp test_glossaries
lualatex --output-dir _tmp test_glossaries.tex
```
everything is going smooth.

As you can see, the only difference between the two setups is the change in the directory name from `.tmp` (starting with a period ".") to `_tmp` (starting with an underscore "_"). I believe that a directory starting with a period "." may be misinterpreted (e.g. as an extension, like .log) due to some path management. I do not know a lot about Java so I'm not really able to figure out where this issue may come from.

### Additional information
- *OS:* Windows 10
- *LaTeX distribution:* MiKTeX 21.10
- *bib2gls:* 2.9

**Comment by nlct** [comment]
It's not a bug, it's a security setting (see  section 1.6 of the `bib2gls` manual). TeX Live comes with security settings `openin_any` and `openout_any` that determine which files are permitted read or write access. These default to `a` (any) for read access and `p` (paranoid = disallows dot files and disallows going to parent directories and restricts absolute paths to be under `$TEXMFOUTPUT`) for write access. If `bib2gls` is unable to obtain these values, it uses TeX Live's default settings. Unfortunately, MiKTeX doesn't provide these values.

If you really want to allow dot files under MiKTeX, you will need to define the environment variable `openout_any` to `a`. To test it run `kpsewhich --var-value=openout_any`. This should print a line containing a single character `a`, `r` or `p`. (This is how `bib2gls` obtains the setting.)
