### ISSUE TITLE
Simple idea

### ISSUE THREAD

**Issue by Martin-2019** [nlct/bib2gls#18]
Dear maintainer,

I would like to propose to add the possibility to print page numbers in dictionaries created with the bib2gls application.

From my point of view, an ideal solution would be the ability to generate in a dictionary or dictionaries, simultaneously: the page number referring to the content and the end index.

It seems to me that this option would be very helpful, for users of the package?

**Comment by nlct** [comment]
Do you mean something like this:
```latex
\documentclass{book}
\begin{filecontents*}{\jobname.bib}
@entry{ant,
  name={ant},
  description={small insect}
}
@entry{aardvark,
  name={aardvark},
  description={mammal that feeds on \glspl{ant}}
}
\end{filecontents*}

\usepackage[record,stylemods={mcols,bookindex}]{glossaries-extra}

\GlsXtrLoadResources[selection=all]

\renewcommand{\glsextrapostnamehook}[1]{\glsadd{#1}}
\begin{document}

\printunsrtglossary[style=mcoltreegroup,title={Dictionary}]

\printunsrtglossary[style=bookindex,title=Index]
\end{document}
```
This can't index until the `.glstex` file has been created so, if the file is called `test.tex`, then the build process is:
```bash
pdflatex test
bib2gls -g test
pdflatex test
bib2gls -g test
pdflatex test
```
This has a one-page dictionary on page 1:

> **A**
> **aardvark** mammal that feeds on ants 1, 3
> **ant** small insect 1, 3

The index is on page 3:

> **A**
> aardvark 1, 3
> ant 1, 3

Alternatively:

```latex
\documentclass{book}
\begin{filecontents*}{\jobname.bib}
@entry{ant,
  name={ant},
  description={small insect}
}
@entry{aardvark,
  name={aardvark},
  description={mammal that feeds on \glspl{ant}}
}
\end{filecontents*}

\usepackage[record,stylemods={mcols,bookindex}]{glossaries-extra}

\newcommand*{\mainencap}[1]{\glsnumberformat{#1}}
\newcommand*{\indexencap}[1]{\glsnumberformat{#1}}

\GlsXtrLoadResources[selection=all,save-primary-locations=remove,
 primary-location-formats={indexencap}]

\begin{document}

\renewcommand{\glsextrapostnamehook}[1]{\glsadd[format=mainnencap]{#1}}
\printunsrtglossary*[style=mcoltreegroup,title={Dictionary}]{%
  \renewcommand{\GlsXtrLocationField}{primarylocations}%
}

\renewcommand{\glsextrapostnamehook}[1]{\glsadd[format=indexencap]{#1}}
\printunsrtglossary[style=bookindex,title=Index]
\end{document}
```
This has a one-page dictionary on page 1:

> **A**
> **aardvark** mammal that feeds on ants 3
> **ant** small insect 3

The index on page 3:

> **A**
> aardvark 1
> ant 1

If you want to use `hyperref` as well, you'll need to change the hyperlink prefix to prevent duplicate targets:

```latex
\documentclass{book}
\begin{filecontents*}{\jobname.bib}
@entry{ant,
  name={ant},
  description={small insect}
}
@entry{aardvark,
  name={aardvark},
  description={mammal that feeds on \glspl{ant}}
}
\end{filecontents*}

\usepackage[colorlinks]{hyperref}
\usepackage[record,stylemods={mcols,bookindex}]{glossaries-extra}

\newcommand*{\mainencap}[1]{\glsnumberformat{#1}}
\newcommand*{\indexencap}[1]{\glsnumberformat{#1}}

\GlsXtrLoadResources[selection=all,save-primary-locations=remove,
 primary-location-formats={indexencap}]

\begin{document}

\renewcommand{\glsextrapostnamehook}[1]{\glsadd[format=mainnencap]{#1}}
\printunsrtglossary*[style=mcoltreegroup,title={Dictionary},prefix=dictionary]{%
  \renewcommand{\GlsXtrLocationField}{primarylocations}%
}

\renewcommand{\glsextrapostnamehook}[1]{\glsadd[format=indexencap]{#1}}
\printunsrtglossary[style=bookindex,title=Index]
\end{document}
```

**Comment by Martin-2019** [comment]
**Dear Doctor Nicola Talbot!**

I would like to thank you for responding so quickly, and to say that it meets my expectations is almost like saying nothing.

As a man of science who has recently started using LaTeX in his work - in the field of chemistry - I am impressed every day by people's ingenuity and creativity.
My search has led me to the perfect solution - Your bib2gls application, whose full capabilities I will certainly not use for many years yet... I am deeply impressed by Your achievements.

**And I would like to express my sincere appreciation**

Marcin Kloske Ph.D.

**Comment by nlct** [comment]
Thank you for your feedback. :-) Since this has solved your problem I'll close this issue.
