### ISSUE TITLE
bib2gls missing form Ubuntu (Ardy)

### ISSUE THREAD

**Issue by usharf** [nlct/bib2gls#2]
There seem to be no package available on Ubuntu (Ardy, was suppose to be packaged with `texlive`) which can provide `bib2gls`... was not sure what was the problem and weather I should report a bug.

**Comment by nlct** [comment]
Some of the Linux distributions don't have the latest version of TeX Live and `bib2gls` was only added in 2017 (the release date for version 1.0 was 2017-09-09), so it may just be that Ubuntu has an older version of TL that doesn't include `bib2gls`. Alternatively, Ubuntu may not include all components of TeX Live. I think you need to contact the Ubuntu developers as I don't know how they determine what software to include. I just upload each new release to CTAN (https://ctan.org/pkg/bib2gls) where it can be picked up by the TeX distributions if they want to include it.

**Comment by usharf** [comment]
Ok. Got it. I've switched to manage Texlive with tlmgr and things seem to be more complete and predictable (dependencies though are not...)
