### ISSUE TITLE
Conversion of .bib files to glossaries-extra resources fails due to parsing errors

### ISSUE THREAD

**Issue by martinKorp** [nlct/bib2gls#22]
With version bib2gls 3.1 (2022-11-05) it seems not possible anymore to convert .bib files to glossaries-extra resources under Linux (so far we were using bib2gls version 2.7 (2020-07-11) which worked perfectly fine). The problems seems to be related to the parsing of active catcodes in .aux files. I have run `bib2gls` in debug mode and attached the corresponding output (see file `bib2glsDebug.log`). I have also attached the .glg file and .aux file in case that you need it (see `glossary.glg` and `glossary.aux`). You can find all three files in the attached .zip file.
[bib2gls.zip](https://github.com/nlct/bib2gls/files/10070971/bib2gls.zip)

**Comment by nlct** [comment]
Can you try the attached [bib2gls.zip](https://github.com/nlct/bib2gls/files/10074636/bib2gls.zip)

**Comment by martinKorp** [comment]
I have tried it out and the parsing of the active catcodes in the .aux file seems to be fine now. However, now the parsing of the LaTeX command `\shorthandoff{=}` in the .aux file is causing some problems. I have attached again the debug output of the tool as well as the .glg and .aux file in case that you need it.
[bib2gls.zip](https://github.com/nlct/bib2gls/files/10079001/bib2gls.zip)

**Comment by nlct** [comment]
Thank you for your feedback. The `\shorthandoff{=}` part is just a warning. I think the real problem is because `=` has been made active so it interferes with the key=value list. I'll look into.

**Comment by nlct** [comment]
Actually, I was wrong about `\shorthandoff{=}` not being significant. That ought to change `=` back to other. Can you try 
[bib2gls.zip](https://github.com/nlct/bib2gls/files/10085397/bib2gls.zip)
This should ignore category code changing commands by default.

**Comment by martinKorp** [comment]
I have tried out the new version and now everything was working as expected. Thanks a lot for fixing this issue so quickly!

**Comment by nlct** [comment]
Glad it works! Thank you for your feedback. I'll upload the new version to CTAN.
