### ISSUE TITLE
bib2gls fails with NullPointerException if TikZ is loaded and .bib file contains @compoundset entry

### ISSUE THREAD

**Issue by vcspth** [nlct/bib2gls#23]
### Example
This is essentially a stripped down version of the example discussed at the end of section 4.10 in the bib2gls user manual, with an additional `\usepackage{tikz}`.

_test.tex_
```
\documentclass{article}

\usepackage{tikz}
\usepackage[record]{glossaries-extra}

\GlsXtrLoadResources[src={bacteria}]

\begin{document}
\mgls{cbot}
\printunsrtglossary
\end{document}
```

_bacteria.bib_
```
@abbreviation{clostridium,
  short={C.},
  long={Clostridium}
}

@index{botulinum,
  parent={clostridium}
}

@index{perfringens,
  parent={clostridium}
}

@compoundset{cbot,
  elements={clostridium,botulinum}
}

@compoundset{cperf,
  elements={clostridium,perfringens}
}
```

### Steps to reproduce

1. Compile `test.tex` with either `pdflatex test` or `lualatex test`
2. Run `bib2gls --debug test`

`bib2gls` exits with status 3 and prints the following error message.
```
Error: NullPointerException
java.lang.NullPointerException
	at com.dickimawbooks.bib2gls.GlsResource.processData(GlsResource.java:7792)
	at com.dickimawbooks.bib2gls.GlsResource.processBibData(GlsResource.java:8306)
	at com.dickimawbooks.bib2gls.GlsResource.processData(GlsResource.java:7391)
	at com.dickimawbooks.bib2gls.Bib2Gls.process(Bib2Gls.java:2717)
	at com.dickimawbooks.bib2gls.Bib2Gls.main(Bib2Gls.java:6616)
```

No `test.glstex` file is created.

### Some notes
1. Removing `\usepackage{tikz}`  yields a working example.
2. Swapping `\usepackage{tikz}` and `\usepackage{glossaries-extra}` makes _no_ difference.
3. Removing the `@compoundset` entries from `bacteria.bib` and using `\multiglossaryentry` instead yields a working example.
4. In particular, non-multi entries work perfectly fine, whether TikZ is loaded or not.

I tested the above example with various combinations of

- `pdflatex` and `lualatex`,
- macOS (arm64) and ArchLinux (x86_64), and
- bib2gls v3.2 (as shipped with TeXLive/MacTeX 2023) and bib2gls3.3 (self-compiled).

Using `\multiglossaryentry` instead of `@compoundset` is a viable workaround but it feels odd to define some entries in the .bib file and others in TeX. A proper fix would be very nice :-).

**Comment by nlct** [comment]
This is strange. If `tikz` is commented out, the following line is correctly written to the `aux` file:
```tex
\@glsxtr@mglsrefs{cbot}
```
This is written by `\mgls` to allow `bib2gls` to pick up the reference. With `tikz`, this line no longer appears in the `aux` file.

So there are two problems. The first is that `bib2gls` isn't gracefully handling no `\@glsxtr@mglsrefs` in the `aux` file when `@compoundset` is in the `bib` file. That's easy to fix, but doesn't solve the underlying problem. The second is that loading `tikz` is somehow interfering with the write to aux performed by `\mgls` (but it doesn't interfere with aux records written by `\gls`). That will require further investigation and will have to be addressed in `glossaries-extra.sty`.

**Comment by nlct** [comment]
The `NullPointerException` is now fixed in commit 7153420. As from the next release (version 3.4) a message will be written to the transcript file if `@compoundset` is found in the bib file(s) but no mgls record is found in the aux file.

I've opened an issue on the [glossaries-extra bug tracker](https://www.dickimaw-books.com/bugtracker.php?key=262) regarding the missing mgls record.

**Comment by nlct** [comment]
Workaround: add `\mglsWriteSeparateRefsTrue` to the document preamble.

**Comment by nlct** [comment]
I've uploaded both `glossaries-extra` v1.52 and `bib2gls` v3.4 to CTAN. They should make their way into the TeX distributions in the next couple of days (`bib2gls` is a day behind `glossaries-extra`).
