### ISSUE TITLE
Unable to recognize entries after chapters with non English titles

### ISSUE THREAD

**Issue by jiaojiaodubai** [nlct/bib2gls#24]
> OS: Windows 11
> LaTex: TeX Live 2023
> bib2gls Version: bib2gls 3.2 (2022-11-24)
> Compilation order:` xelatex $->$ bib2gls --group main $->$ xelatex`

I am trying to add a vocabulary to my **Chinese document**, which includes Chinese terms and their corresponding English forms. To facilitate the management of a large number of vocabulary, I used bib2gls.

But I found that **entries can only be displayed normally in the first chapter, and only "??" is displayed in the subsequent second chapter**. And if I change the title of Chapter 2 to English, then everything is normal.

I checked the `.aux` file and found that the entries used in Chapter 2 have already been recorded in the. aux file, so it seems that Bib2bls is unable to read these contents properly.

Below, I provide a brief example, which shows that starting from the second chapter with a Chinese title (chapter 3), the newly added entries will not display properly (even if the subsequent title is changed to English).

※: `ctexbook` is a document class provided by TeX Live's built-in package [ctex](https://www.ctan.org/pkg/ctex).

[sample.zip](https://github.com/nlct/bib2gls/files/12388316/sample.zip)

**Comment by nlct** [comment]
Your example bib file has a duplicate label. This causes an error from `bib2gls`:
```
Error: symbols.bib:15: Repeated entry 'sym1'
```
There's no `sym3` in the `symbols.bib` file so the reference `\gls{sym3}` is undefined and produces `??`.

I'm guessing the final entry in the `bib` file should have `sym3` not `sym1` as the label.

With this correction, your test file works fine with `bib2gls` v3.4. I don't know why changing the chapter title to English should make a difference. The following modification to your document works fine for me:
```latex
% Encoding: UTF-8
\documentclass{ctexbook}

\usepackage[record]{glossaries-extra}
\GlsXtrLoadResources[
  src={symbols}
]

\begin{document}
\chapter{一一一}
\gls{sym1}
\chapter{二}
\gls{sym1}，\gls{sym2}
\chapter{三}
\gls{sym2}，\gls{sym3}
\chapter{亖}
\gls{sym2}，\gls{sym3}
\printunsrtglossary
\end{document}
```
with `symbols.bib`:
```bibtex
% Encoding: UTF-8
@symbol{sym1,
    name={一},
    description={one}
}

@symbol{sym2,
    name={二},
    description={two}
}

@symbol{sym3,
    name={三},
    description={three}
}
```

If you're still getting a problem, try upgrading to the latest version of `bib2gls` and, if the problem still occurs, provide the `.glg` transcript file.

**Comment by jiaojiaodubai** [comment]
Sorry, the missing 'sym3' was an mistake I made while creating the sample file.

I attempted to upgrade bib2gls to V3.4 (by simply replacing the original file with the latest release file in this repository), but still encountered the issue of not being able to display new entries after the Chinese chapter title.
![image](https://github.com/nlct/bib2gls/assets/63148861/16a25d2a-378d-4e1a-9998-edddd4e78c01)

Below, I have provided the complete test files.
[sample.zip](https://github.com/nlct/bib2gls/files/12388606/sample.zip)

**Comment by nlct** [comment]
The best way of upgrading to a new version in TeX Live is to use the TeX Live Manager.

I'm sorry, I'm getting a 404 not found for your attached `sample.zip`. Could you copy and paste a simple document inline that demonstrates the problem.

Here are some general tips:

- Search the `.log` file for messages like "Package glossaries-extra Warning: Glossary entry \`[...]' has not been defined" and search for the [...] part in the `.bib` file to make sure that the label is correct. Be careful of spurious spaces.
- Search the `.glg` file for any warnings or error messages. If you add `--verbose` (after `--group`) there will be more information.

**Comment by jiaojiaodubai** [comment]
Thank you. I have updated the attachment of the previous comment and it can now be downloaded normally. I will try using the method you recommended to update bib2gls first.

**Comment by nlct** [comment]
Thank you, I'm able to download the attachment now. It works fine for me with `bib2gls` v3.4, `glossaries-extra` v1.52 and `glossaries` v4.52. Try changing the `bib2gls` invocation in your build file (`Compile-It.ps1`) to:
```
bib2gls --group --debug test
```
(This gives a lot more information than just `--verbose`.)

**Comment by jiaojiaodubai** [comment]
It's very strange. I uninstalled and reinstalled my TeX Live 2023, and then updated all packages (including bib2gls), but the results were still as disappointing as before.
The following are the compilation results with the "-- debug" parameter.
[sample.zip](https://github.com/nlct/bib2gls/files/12397053/sample.zip)

**Comment by nlct** [comment]
It seems to be exiting from the aux file too soon, but I don't know why it's happening. I can't reproduce it. I've added an extra set of debugging information to try to find out why.

Can you replace your copies of `bib2gls.jar` and `texparserlib.jar` with the files in the attached 
[jarfiles.zip](https://github.com/nlct/bib2gls/files/12412951/jarfiles.zip) and changed the invocation to:
```
bib2gls --group --debug-mode all test
```
and send me the sample files again.

**Comment by jiaojiaodubai** [comment]
For the sake of comparison, I have added two subdirectories to the new sample file.
[sample.zip](https://github.com/nlct/bib2gls/files/12414226/sample.zip)

**Comment by nlct** [comment]
Thank you. Here's a summary so far:

- You're using Windows. I'm using Linux.
- We're both using Java 17.0.8, the same versions of `bib2gls`, `texparserlib.jar`, and have the same aux files.
- Your locale is zh-CN so I'm running bib2gls with `--locale zh-CN` to match.
- Aside from path names, everything is the same in our `.glg` files until after the `\numberline` in the first `\@writefile` is encountered in the aux file.
- We both have UTF-8 set as the file encoding. However, your `glg` file doesn't seem to have the correct encoding.

For example, my `glg` file has:
```
append-prefix-field-exceptions: ' (0x27) - (0x2D) ~ (0x7E) ‐ (0x2010) ‑ (0x2011) ’ (0x2019)
```
but the corresponding line in yours shows as:
```
append-prefix-field-exceptions: ' (0x27) - (0x2D) ~ (0x7E) ©\ (0x2010) ? (0x2011) ¡¯ (0x2019)
```
and a little further down in mine:
```
Parsing fields for entry 'sym1'
>> name={一}
=>> name={一}
```
but yours has:
```
Parsing fields for entry 'sym1'
>> name={Ò»}
=>> name={Ò»}
```

So it's possible there's an encoding mismatch. Can you open the Windows command prompt and try the following:
```
cd C:\VIP\WorkSpace\LatexHome\sample
java -Dfile.encoding=UTF-8 -jar C:\texlive\2023\texmf-dist\scripts\bib2gls.jar --group --debug-mode all test
```

**Comment by jiaojiaodubai** [comment]
I have made some slight changes to the code above and the results are satisfactory.

There are two changes. 
1. The path to `bib2gls. jar` should be in the `bib2gls\` directory instead of the `scripst\` directory, that is,`<foo>\texmf-dist\scripts\bib2gls\bib2gls. jar`. I don't know if this is a typo or a difference between different operating systems.
2. Windows' modern terminal PowerShell is temporarily unable to accept parameters containing a period of `.` So I followed the suggestion of @mklement0 to use quotation marks to surround the first parameter in order to function properly<sup>[1]</sup>.

In addition, I have done some research to explain this issue.
1. The character set of Windows depends on the system's region and language settings. For China, a schema called gb2312 is used<sup>[2]</sup>.
2. The default decoding scheme of the JVM is read from the operating system<sup>[3]</sup>.

I hope this information can help you fix this bug.

[1]: <a name="1">[mklement0's suggestion](https://github.com/PowerShell/PowerShell/issues/15541#issuecomment-1329828092)
[2]: <a name="2">[encoding Class](https://learn.microsoft.com/en-us/dotnet/api/system.text.encoding?view=net-6.0#remarks)</a>
[3]: <a name="3">[Default Charset](https://www.baeldung.com/java-char-encoding#1-default-charset)</a>
[sample.zip](https://github.com/nlct/bib2gls/files/12419748/sample.zip)

**Comment by nlct** [comment]
Sorry, I made a mistake. You're right, the path should be `C:\texlive\2023\texmf-dist\scripts\bib2gls\bib2gls.jar`

If you always want UTF-8 for all your installed Java applications (not just `bib2gls`) you can set the environment variable [`JAVA_TOOL_OPTIONS`](https://docs.oracle.com/en/java/javase/17/docs/specs/jvmti.html#tooloptions) to include `-Dfile.encoding=UTF-8`. This will set the default for the JVM. 

Otherwise, if you only want UTF-8 for `bib2gls` then you can use `--tex-encoding` to specify the encoding for the `.glstex` files. The document encoding is picked up in the `aux` file, but that's too late for the `aux` file itself. Try:
```
bib2gls --tex-encoding UTF-8 --group test
```

**Comment by nlct** [comment]
Summary of encoding used for the different files:

- Writing the `glg` transcript file: default encoding.
- Reading the document `log` file: default encoding.
- Reading the `aux` file: the `--tex-encoding` setting, if supplied, or UTF-8 if `fontspec` detected in the log file, otherwise the default encoding.
- Reading the `bib` files: the `charset` resource option, if supplied, or the encoding specified in the `% Encoding: ` line of the `bib` file, otherwise the default encoding.
- Writing the `glstex` files: the `--tex-encoding` setting, if supplied, or UTF-8 if `fontspec` detected in the log file, or the document encoding picked up from the `aux` file, otherwise the default encoding.

The next version of `bib2gls` will have a new switch `--default-encoding` to set the default encoding to override the JVM default, but hopefully `--tex-encoding` should be sufficient for your example if you don't want to globally change the JVM defaults.

**Comment by jiaojiaodubai** [comment]
Thank you for providing these flexible and constructive solutions.
