### ISSUE TITLE
Support for non-default output directory for automake feature

### ISSUE THREAD

**Issue by user202729** [nlct/bib2gls#31]
Hi, thanks for maintaining the package. (good to see it is well maintained. Although I don't use it myself)

This is not about the bib2gls tool itself, it's about `glossaries-extra` package --- the `automake` feature doesn't support non-default `output-directory`.

An example can be found in this question https://tex.stackexchange.com/questions/728356/why-latexmk-is-not-able-to-run-shell-escape-with-auxdir

Looking through the code in the `.sty`, fortunately the fix is rather simple (I tested with the sty file, although you'll need to apply the corresponding patch to the `.dtx` file, I don't know where you put it)

```diff
--- /tmp/glossaries-extra.sty   2024-10-11 11:52:23.456810931 +0700
+++ glossaries-extra.sty        2024-10-11 11:56:02.893483011 +0700
@@ -580,6 +580,10 @@
     }%
   }%
 }
+\newcommand*{\@glsxtr@outputdir}{.}
+\define@key{glossaries-extra.sty}{outputdir}{%
+  \renewcommand*{\@glsxtr@outputdir}{#1}%
+}
 \newcommand*{\glsxtrabbrvtype}{\glsdefaulttype}
 \newcommand*{\@glsxtr@abbreviationsdef}{}
 \@ifpackageloaded{babel}%
@@ -7036,8 +7040,8 @@
     {\protected@write\@auxout{}{\string\glsxtr@linkprefix{\glolinkprefix}}}%
   \let\glsxtr@writefields\relax
   \ifglsautomake
-    \IfFileExists{\jobname.aux}%
-    {\immediate\write18{bib2gls \jobname}}{}%
+    \IfFileExists{\@glsxtr@outputdir/\jobname.aux}%
+    {\immediate\write18{bib2gls --dir=\@glsxtr@outputdir/ \jobname}}{}%
     \ifx\@gls@doautomake\@gls@doautomake@err
        \let\@gls@doautomake\relax
     \fi
```

With that, I can change the package load line to `\usepackage[record, automake, outputdir=build/]{glossaries-extra}` and it would work for the example.

(for comparison, other packages such as `tikz-externalize` uses a command instead of package option to set the output directory e.g. `\tikzsetexternalprefix{build/}`)

-----

By the way, starting from TeX Live 2024, it is actually possible to obtain the output directory automatically : https://tex.stackexchange.com/questions/294931/access-value-of-output-directory/621510#621510 . You may want to consider using that so the user wouldn't need to specify the output directory.

**Comment by nlct** [comment]
Thank you for the suggestion. I will add a check for the existence of the environment variable `TEXMF_OUTPUT_DIRECTORY` if `automake` has been switched on, but I'll put it in the base `glossaries` package rather than `glossaries-extra` as it would also be useful with `automake=makegloss`.

**Comment by nlct** [comment]
I've added support to `glossaries` v4.55, which I've just uploaded to CTAN. The next version of `glossaries-extra` (v1.54), which I hope to release soon, should be able to pick up the change.
