### ISSUE TITLE
BibGlsTexApp seems to be missing in the current jar file. 

### ISSUE THREAD

**Issue by tbr-git** [nlct/bib2gls#32]
Hello,

When I try to run the most recent version of bib2gls, I get a class not found exception:

`NoClassDefFoundError: com/dickimawbooks/bibgls/common/BibGlsTeXApp`

Inspecting the jar files in the release, which I "installed" from CTAN, the "common" packages seems to be missing and thus the required class.

**Comment by nlct** [comment]
Do you have version 4.0 or 4.0a? Some files were missing in my original upload and I had to reupload them (and had to modify the version slightly).

**Comment by tbr-git** [comment]
I installed the verison that I tested yesterday from MikTex. There is says version 4.0.
However, I just took a look at the jar file found on CTAN, (on the page, the current version 4.0a is reported) (https://mirrors.ctan.org/support/bib2gls/bib2gls.jar), and is also does not seem to contain the commons package.

**Comment by nlct** [comment]
It may be that MikTeX hasn't picked up v4.0a yet. The common library is `bibglscommon.jar`. All files are now showing on the main CTAN site but the CTAN mirrors may not have caught up.

**Comment by tbr-git** [comment]
Yes, I just found and added it manually. Now, it works. The problem seems definitely related to MikTeX.
Thanks for the swift response.
