### ISSUE TITLE
Modifying dual entry display in glossary with bib2gls and glossaries extra, altlistgroup glossarystyle

### ISSUE THREAD

**Issue by Delanii** [nlct/bib2gls#6]
Hello Mrs. Talbot,
I am trying to find a way how to manipulate with dual entry display in altlistgroup style glossary. I am using glossaries-extra and bib2gls.

In my document, I am having list of abrreviations, main glossary and index. All of the entries are also displayed in index. Some of them are abbreviations, that require also description. For that I have chosen to create dual entries for them. In fact, they are tercial entries (being also in index), but I hope that is not problem.

The default behaviour of this setting (as far as I was able to see) is, that the dualabbreviationentry displays in main glossary (altlistgroupstyle) its "long form" (instead of "name") and "description."

How can I change that? Ideally to display again "name," bacause in that way I could manipulate with that field to display any text I would need. Alternatively, if this couldnt be done, the "short" field would be for me more suitable than "long" field.

Please, allow me to support an example of my situation, that is using package filecontents to create respective .bib files, hopefully to your convenience:

```
% arara: lualatex: { shell: true }
% arara: bib2gls: { group: true }
% arara:  lualatex: { synctex: true, shell: true }
% arara: bib2gls: { group: true }
% arara:  lualatex: { synctex: true, shell: true }

\documentclass[12pt,twoside]{book}

\usepackage [czech] {babel}
\usepackage[T1]{fontenc}
\usepackage{fontspec}

\usepackage{filecontents}	

%Entries

\begin{filecontents}{entries.bib}
@entry{singleentry,
  name = {Single entry},
  description = {entry description}
}
\end{filecontents}{entries.bib}

%Abbreviations

\begin{filecontents}{abbrvs.bib}
% Encoding: UTF-8
@abbreviation{aa,
  short = {AA},
  long = {Absolute assignment}
}
\end{filecontents}{abbrvs.bib}

%Duals

\begin{filecontents}{duals.bib}
% Encoding: UTF-8
@dualabbreviationentry{dual,
  long = {As Low As Reasonably Achievable},
  short = {ALARA},
  name = {ALARA},
  description = {{Dual entry description}
}
}
\end{filecontents}{duals.bib}

\usepackage{array}
\usepackage{booktabs}
\usepackage{longtable}

\usepackage[record, nopostdot, abbreviations,
		index,%
                    nostyles, stylemods={all},
                    ]{glossaries-extra}

\setglossarystyle{long-booktabs}

\setabbreviationstyle[acronym]{long-short-user}
\renewcommand*{\entryname}{Abbreviation}
\renewcommand*{\descriptionname}{Full meaning}

\GlsXtrLoadResources[selection={all},%
			src={entries,abbrvs,duals},%
			 entry-type-aliases={
  				abbreviation=dualindexabbreviation,
  				entry=dualindexentry,
				dualabbreviationentry=tertiaryindexabbreviationentry},
			type={index},
			label-prefix={idx.},
 			dual-prefix={},
 			cs-label-prefix={},
			sort={en},
 			sort-field={name},
 			dual-sort={en},
 			charset=UTF-8,%
			combine-dual-locations={primary},
			cs-label-prefix={},
			]

\begin{document}
\renewcommand{\glsextrapostnamehook}[1]{\glsadd[format=hyperbf]{#1}}
\printunsrtglossary[type={abbreviations}, title=Abbreviations]

\cleardoublepage

\setglossarystyle{altlistgroup}
\printunsrtglossary[type={main}, title=My Glossary, toctitle=My Glossary]

\renewcommand{\glsextrapostnamehook}[1]{}
\printunsrtglossary[type=index,style=bookindex]

\cleardoublepage

\end{document}
```

I know this is not bug report per say, more like an issue I am asking you to help me with. I have tryed to find answer in your documentation, but as it is very thorough and extensive, I wasn´t able to find it.
I also tryed to find help at TeX Stack Exchange, but wasn´t succesfull either.
Thank you very much, regards

Tomas Krulis

**Comment by nlct** [comment]
The dual and tertiary terms are defined by the command `\bibglsnewtertiaryindexabbreviationentrysecondary`. The default definition is:
```latex
\providecommand{\bibglsnewtertiaryindexabbreviationentrysecondary}[8]{%
  \newabbreviation[#3]{#1}{#6}{#7}%
  \longnewglossaryentry*{#2}%
  {name={\protect\bibglsuselongfont{#7}{\glscategory{#1}}},#4}%
  {#8}%
}
```
The `\longnewglossaryentry` part defines the tertiary entry. This sets the `name` to use the long form:
```latex
name={\protect\bibglsuselongfont{#7}{\glscategory{#1}}}
```
So you need to provide a new definition that uses the short form instead. For example:
```latex
\glsrenewcommand{\bibglsnewtertiaryindexabbreviationentrysecondary}[8]{%
  \newabbreviation[#3]{#1}{#6}{#7}%
  \longnewglossaryentry*{#2}%
  {name={\protect\bibglsuseabbrvfont{#6}{\glscategory{#1}}},#4}%
  {#8}%
}
```

**Comment by Delanii** [comment]
Thank you very much for your help Mrs. Talbot. It works like a charm. As I look upon the changes required, I see only change in one argument. I read through the package documentation, but apparently not carefully enough (or maybe there was change in newest version of bib2gls manual?). Either way, for future reference I managed to find the command provided and his like in bib2gls documentation.
